services:
  influxdb:
    container_name: influxdb-ur3e
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=ur3e
      - DOCKER_INFLUXDB_INIT_PASSWORD=ur3e_pass
      - DOCKER_INFLUXDB_INIT_ORG=ur3e_dt
      - DOCKER_INFLUXDB_INIT_BUCKET=ur3e
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=ur3e-dt-token
    restart: unless-stopped

  grafana:
    container_name: grafana-ur3e
    image: grafana/grafana:11.4.0
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=ur3e
      - GF_SECURITY_ADMIN_PASSWORD=ur3e_pass
    depends_on:
      - influxdb
    restart: unless-stopped

volumes:
  influxdb_data:
  grafana_data:
